# Generated by Django 5.0.2 on 2024-03-15 22:23

import django.db.models.deletion
from django.db import migrations, models
from pages.models import Page, Tutorial, Video

def exchange(apps, schema_editor):
    tutorials = []
    videos = []
    page_updates = []

    for page in Page.objects.all():
        if page.content:
            tutorials.append(Tutorial(content=page.content, page=page))
            page_updates.append(Page(pk=page.pk, type='tutorial'))
        if page.video:
            videos.append(Video(video=page.video, page=page))
            page_updates.append(Page(pk=page.pk, type='video'))

    Tutorial.objects.bulk_create(tutorials)
    Video.objects.bulk_create(videos)
    Page.objects.bulk_update(page_updates, ['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_type_video_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('video', 'Video')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=54)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pages.page')),
            ],
        ),
        migrations.RunPython(exchange)
    ]
