
# Generated by Django 5.0.2 on 2024-03-15 22:23

import django.db.models.deletion
from django.db import migrations, models
from pages.models import Page, Tutorial, Video

def exchange(apps, schema_editor):
    tutorials = []
    videos = []
    page_updates = []

    for page in Page.objects.all():
        if page.content:
            tutorials.append(Tutorial(content=page.content, page=page))
            page_updates.append(Page(pk=page.pk, type='tutorial'))
        if page.video:
            videos.append(Video(video=page.video, page=page))
            page_updates.append(Page(pk=page.pk, type='video'))

    Tutorial.objects.bulk_create(tutorials)
    Video.objects.bulk_create(videos)
    Page.objects.bulk_update(page_updates, ['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_tutorial_content_alter_tutorial_page_and_more'),
    ]

    operations = [
        migrations.RunPython(exchange)
    ]
